### PR TITLE
Handle Preview messages (#61)

### PR DESCRIPTION
**Pull request by ezequielc**
* handle multiple postMessage() types to support display data

### CODE REVIEW

**Comment by ezequielc** [comment]
@alex-deaconu Please review. Thanks

**Comment by stulees** [comment]
@fjvallarino @santiagonoguez FYI, lets follow what @ezequielc did here and do a PR for review when merging `master` into `build/stable`. It's a good way to prevent mistakes, thanks @ezequielc

**Comment by santiagonoguez** [comment]
@stulees ok !

**Comment by ezequielc** [comment]
@stulees  @fjvallarino @santiagonoguez There is one annoyance with this approach because `build/stable` gets ahead of `master` after the PR merge, which is not ideal. 
I think we can revisit/improve this process, so up to you if you prefer to follow this or continue to follow the usual. Thanks!

**Pull request merged**
