### PR TITLE
Refactor getComponentAsync() helper function to decouple it from "configured" event

### PR DESCRIPTION
**Pull request by stulees**
## Description
Refactored `getComponentAsync()` to make it reusable based on a new `state` parameter. This decouples the function from specifically listening/handling a components _configured_ event and sets up future usage for components reporting _ready_.

Introduced new `rise-constants.js` and added component states _configured_ and soon to be used _ready_ . 

Updated all direct and indirect usages of `getComponentAsync()` to ensure the _configured_ state is used where applicable. 

## Motivation and Context
Incremental steps towards implementing templates reporting "ready" milestone as per [design](https://docs.google.com/document/d/1yuyRWQf1kUpnsMajJSlsHf_U8a3npmM_l1j0lFMXkOA/edit#heading=h.8wh44uuwg8by). This is part of the fix towards [Issue 865](https://github.com/Rise-Vision/rise-launcher-electron/issues/865)

## How Has This Been Tested?
Using Charles to map to local version of common-template.min.js and with this schedule https://apps.risevision.com/schedules/details/822cbbd2-ad76-44c1-acc6-cff355e1c133?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

 - [ ] Common template has been tested on Player
 - [X] Common template has been tested on Chrome OS Player
 - [ ] Common template has been tested on Web Player
 - [X] Common template has been tested in a Shared Schedule
 - [X] Common template has been tested in Apps Template Editor
 - [ ] Common template has been tested in embedded template

## Release Plan:
- Only merging to the `feature/track-components-ready` branch for now.

#### Release Checklist Items Skipped?
none

### CODE REVIEW

**Comment by stulees** [comment]
@olegrise Please review, thanks. Reminder, coveralls is low because of our previous task of stopping logs to client-side-events whereby we disabled a bunch of tests. We'll be addressing that at a later date. 

@alex-deaconu @ezequielc FYI, I'll tag you both on all changes we make towards this 865 milestone, however your review is completely optional. Thanks!

**Comment by alex-deaconu** [comment]
@stulees I'm not sure if you're aware of this usage for the function: https://github.com/Rise-Vision/rise-common-component/blob/master/src/rise-element.js#L99. Thanks.

**Comment by stulees** [comment]
@alex-deaconu I was aware in my code review for the design but forgot about it in these changes. Thanks for reminding me! To avoid having to change that rise-common-component code and update all components, I will default a `state` to be "configured" if it's not provided. Sound okay to you?

**Comment by alex-deaconu** [comment]
@stulees sounds good. However that only applies for `getRiseRootElements` so playlist items would not work correctly. I just wanted to make sure you're aware of that particular usage. Thanks!

**Comment by stulees** [comment]
@alex-deaconu In thinking this over more, I'm going to scrap this PR in favour of just having a completely separate `getComponentsReadyAsync()` function and that way avoid any complications given `getComponentAsync()` is used in many places. Thanks for the feedback!

**Comment by alex-deaconu** [comment]
@stulees sounds good. One thing I would note is you don't have to stick with the same naming convention for your new function; ie. you can call it `onComponentReady` to indicate the promise resolves on ready. Just a thought. Thanks!

**Pull request closed without merging**
