### PR TITLE
Track components reporting ready

### PR DESCRIPTION
**Pull request by stulees**
## Description
Adding a new function `RisePlayerConfiguration.Helpers.trackComponentsReady` function to track when components have reported _ready_ and initiating this within the initial execution of `configure()`.

Running a 60 second validation that the template received _ready_ from all components, if it did not, it logs a `E...999` code and includes which components did not report ready in the detail. 

## Motivation and Context
Incremental steps towards implementing templates reporting "ready" milestone as per [design](https://docs.google.com/document/d/1yuyRWQf1kUpnsMajJSlsHf_U8a3npmM_l1j0lFMXkOA/edit#heading=h.8wh44uuwg8by) which is part of the fix towards [Issue 865](https://github.com/Rise-Vision/rise-launcher-electron/issues/865)

## How Has This Been Tested?
Added unit tests and tested with locally built version via Charles with this schedule https://apps.risevision.com/schedules/details/822cbbd2-ad76-44c1-acc6-cff355e1c133?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

 - [X] Common template has been tested on Player
 - [X] Common template has been tested on Chrome OS Player
 - [X] Common template has been tested on Web Player
 - [X] Common template has been tested in a Shared Schedule
 - [X] Common template has been tested in Apps Template Editor
 - [ ] Common template has been tested in embedded template

## Release Plan:
- Only merging to feature branch. 

#### Release Checklist Items Skipped?
no

### CODE REVIEW

**Comment by stulees** [comment]
@olegrise Please review, thanks. @alex-deaconu @ezequielc FYI

**Review by olegrise — APPROVED** [review]
@stulees looks good. Curios, were you able to manually, not with unit test, validate the use case when error is reported? Thanks.

**Comment by stulees** [comment]
@olegrise Yes I was on ChrOS player, see these logs

image

**Comment by olegrise** [comment]
@stulees nice! Thanks.

**Pull request merged**
